services:
  tech_library:
    container_name: tech_library_db
    image: mysql:5.7
    hostname: tech-library
    volumes:
      - tech_library_volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: tech_library
      MYSQL_ROOT_PASSWORD: 
    networks:
      - tech_library_network
    restart: unless-stopped

  tech_library_app:
    container_name: tech_library_app
    build: .
    depends_on:
      - tech_library
    ports:
      - "8000:8000"
    networks:
      - tech_library_network
    volumes:
      - tech_library_volume:/app
    environment:
      DB_HOST: tech_library_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_DATABASE: tech_library
      PORT: 8000
      LENGUAGE: es
      DEFAULT_PAGE_SIZE: 9
      JWT_SECRET: 
      ORIGIN: http://localhost:5173
      GITHUB_CLIENT_ID: 
      GITHUB_CLIENT_SECRET: 
      GITHUB_CALLBACK_URL: http://localhost:8000/api/auth/github/callback
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_CALLBACK_URL: http://localhost:8000/api/auth/google/callback
      REDIRECT_URL: http://localhost:5173/login/auth
    command: ["sh", "-c", "wait-port tech_library_db:3306 && npm start"]
    restart: unless-stopped

networks:
  tech_library_network:
    driver: bridge

volumes:
  tech_library_volume:
