services:
  tech_library:
    container_name: tech_library_db
    image: mysql:9
    hostname: tech-library
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: tech_library
      MYSQL_ROOT_PASSWORD: 
    networks:
      - tech_library_network

  tech_library_app:
    container_name: tech_library_app
    build: .
    depends_on:
      - tech_library
    ports:
      - "8000:8000"
    networks:
      - tech_library_network
    environment:
      DB_HOST: tech_library_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: tech_library
      PORT: 8000
      LENGUAGE: es
      DEFAULT_PAGE_SIZE: 9
      JWT_SECRET: 
      ORIGIN: 
      GITHUB_CLIENT_ID: 
      GITHUB_CLIENT_SECRET: 
      GITHUB_CALLBACK_URL: 
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_CALLBACK_URL: 
      REDIRECT_URL: 

    command: ["/usr/src/app/wait-for-it.sh", "tech_library_db:3306", "--", "sh", "-c", "npm run db:create && npm start"]

networks:
  tech_library_network:
    driver: bridge